---


detectors:

  BooleanParameter:
    enabled: false

  ClassVariable:
    exclude:
      - lib/notify/*.rb

  ControlParameter:
    enabled: false

  DuplicateMethodCall:
    max_calls: 3

  FeatureEnvy:
    enabled: false

  NestedIterators:
    max_allowed_nesting: 3

  NilCheck:
    enabled: false

  TooManyStatements:
    enabled: false

  UncommunicativeVariableName:
    enabled: false

exclude_paths:
  - test/
  - adoc-extensions.d/multipage_html5.rb
