# .rubocop.yml
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - lib/utils.rb
    - Gemfile
    - Rakefile
    - adoc-extensions.d/*.rb
    - test/**/*.rb

Layout:
  Enabled: false

# Lint/NonDeterministicRequireOrder:
#   Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/Documentation:
  Exclude:
    - test/**/*.rb

