# .rubocop.yml
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - utils/**/*.rb
    - ./**/Gemfile
    - Rakefile

Layout/LineLength:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/Documentation:
  Exclude:
    - tests/**/*.rb

