source 'https://rubygems.org'
gem 'asciidoctor', '~> 2.0.10'
gem 'asciidoctor-diagram', '~> 2.0.0'
gem 'asciidoctor-pdf', '~> 1.5.0.beta.5'
gem 'rouge'
gem 'concurrent-ruby'
gem 'rake'
gem 'rubocop'
gem 'json'
