asciidoc:
  index:
    file: content/index.adoc
  multipage_level: 3

build:
  dir: /tmp/build
  html_dir: /tmp/build/html

checkers:
  pattern:
      - blacklist: blacklist.txt

search:
  index:
    file: lunrindex.json
    exclude:
      - docinfo*.html

log:
  file: /tmp/log.json

notify:
  slack:
      file: /tmp/slack.json

toc:
  json_file: /tmp/toc.json
  html_file: /tmp/toc.html
