build:
  dir: /tmp/build

checkers:
  pattern:
      - blacklist: blacklist.txt

search:
  index:
    file: lunrindex.json
    exclude:
      - docinfo*.html

log:
  path: /tmp/log.json

notify:
  slack:
      file: /tmp/slack.json


