index:
  default:
    file: content/index.adoc

build:
  dir: /tmp/build

checkers:
  pattern:
      - blacklist: blacklist.txt

search:
  index:
    file: lunrindex.json
    exclude:
      - docinfo*.html

log:
  file: /tmp/log.json

notify:
  slack:
      file: /tmp/slack.json

toc:
  file: /tmp/toc.json
