name: Main

on: [push, pull_request]
env:
  TOOLCHAIN_PATH: .
  TOOLCHAIN_TEST: true

jobs:
  test-and-publish:
    if: contains(toJson(github.event.commits), '[skip ci]') == false
    runs-on: ubuntu-latest

    steps:
    - name: "Install tools"
      run: |
        sudo snap install --classic ripgrep
        rg --version

    - name: "Setup ruby 2.6"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.10
        bundler-cache: false

    - uses: actions/checkout@v1

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: "Install Gems"
      run: |
        gem install bundler:2.3.26
        gem update --system 3.2.3
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: "Running unit tests"
      run: |
        bundle exec rake toolchain:test

    - name: "Linting"
      run: |
        bundle exec rake toolchain:lint

    - name: "Generate rdoc"
      run: |
        bundle exec rake toolchain:rdoc

    - name: "Quality check"
      run: |
        bundle exec rake toolchain:quality

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage/lcov/docs-toolchain.lcov

    - name: "Prepare upload"
      if: endsWith(github.ref, '/master')
      run: |
        mkdir -p public
        mv /tmp/rdoc /tmp/rubycritic coverage public/
        cp public/rubycritic/{overview,index}.html

    - name: "Deploy reports to Github Pages"
      if: endsWith(github.ref, '/master')
      uses: peaceiris/actions-gh-pages@v2
      env:
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
        PERSONAL_TOKEN: ${{ secrets.GITHUB_PAT }}
      with:
        keepFiles: true

    - name: "Show TODOs"
      run: rg -f .github/patterns.txt -t ruby .

