name: Main

on: [push, pull_request]
env:
  TOOLCHAIN_PATH: .

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    # container:
    #   image: ruby:2.6

    steps:
    - name: "Setup ruby 2.6"
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: actions/checkout@v1

    - name: "Install Gems"
      run: |
        bash setup/setup.sh

    - name: "Running unit tests"
      run: |
        rake toolchain:test

    - name: "Linting"
      run: |
        rake toolchain:lint

    - name: "Quality check"
      run: |
        rake toolchain:quality

    - name: "Generate rdoc"
      run: |
        rake toolchain:rdoc

    - name: "Prepare upload"
      run: |
        mkdir -p /tmp/public
        mv /tmp/rdoc /tmp/rubycritic coverage /tmp/public
        ln -s /tmp/rubycritic/{overview,index}.html

    - name: "Deploy reports to Github Pages"
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: /tmp/public
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
