name: Main

on: [push, pull_request]
env:
  TOOLCHAIN_PATH: .
  TOOLCHAIN_TEST: true

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Extract branch name
      shell: bash
      id: extract_branch
      run: |
        echo "GITHUB_REF: "${GITHUB_REF}
        if [[ ${GITHUB_EVENT_NAME} == 'pull_request' ]]; then
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF} | sed 's|refs/pull/\([0-9]\+\)/merge|PR\1|')"
        else
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        fi

    - name: "Install tools"
      run: |
        sudo snap install --classic ripgrep
        rg --version

    - name: "Setup ruby 2.6"
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: actions/checkout@v1

    - name: "Install Gems"
      run: |
        bash setup/setup.sh

    - name: "Running unit tests"
      run: |
        rake toolchain:test

    - name: "Linting"
      run: |
        rake toolchain:lint

    - name: "Generate rdoc"
      run: |
        rake toolchain:rdoc

    - name: "Quality check"
      run: |
        rake toolchain:quality

    - name: "Prepare upload"
      run: |
        mkdir -p public
        ls -l
        mv /tmp/rdoc /tmp/rubycritic coverage public/
        ls -l public/
        ls -l public/rubycritic/
        cp public/rubycritic/{overview,index}.html
        if [[ ${GITHUB_REF##*/} != 'master' ]]; then
          mv public "${GITHUB_REF##*/}"
          mkdir public
          mv "${GITHUB_REF##*/}" public/
        fi

    - name: "Deploy reports to Github Pages (Master branch)"
      if: steps.extract_branch.outputs.branch == 'master'
      uses: peaceiris/actions-gh-pages@v2
      env:
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
        PERSONAL_TOKEN: ${{ secrets.GITHUB_PAT }}
      with:
        keepFiles: true

    - name: "Deploy reports to Github Pages (Dev branches)"
      uses: peaceiris/actions-gh-pages@v2
      env:
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
        PERSONAL_TOKEN: ${{ secrets.GITHUB_PAT }}
        TARGET_FOLDER: ${{ steps.extract_branch.outputs.branch }}
      with:
        keepFiles: true

    - name: "Show TODOs"
      run: rg -f .github/patterns.txt -t ruby .

