name: Main

on: [push, pull_request]
env:
  TOOLCHAIN_PATH: .

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    # container:
    #   image: ruby:2.6

    steps:
    - name: Extract branch name
      shell: bash
      id: extract_branch
      run: |
        if [[ ${GITHUB_EVENT_NAME} == 'pull_request' ]]; then
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF} | sed 's|refs/pull/:\([0-9]\+\)/merge|PR\1|')"
        else
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        fi

    - name: "Setup ruby 2.6"
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: actions/checkout@v1

    - name: "Install Gems"
      run: |
        bash setup/setup.sh

    - name: "Running unit tests"
      run: |
        rake toolchain:test

    - name: "Linting"
      run: |
        rake toolchain:lint

    - name: "Generate rdoc"
      run: |
        rake --tasks
        rake toolchain:rdoc

    - name: "Quality check"
      run: |
        rake toolchain:quality

    - name: "Prepare upload"
      run: |
        mkdir -p public
        ls -l
        mv /tmp/rdoc /tmp/rubycritic coverage public/
        ls -l public/
        ls -l public/rubycritic/
        cp public/rubycritic/{overview,index}.html

    - name: "Deploy reports to Github Pages (Master branch)"
      if: steps.extract_branch.outputs.branch == 'master'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh-pages
        FOLDER: public
        ACCESS_TOKEN: ${{ secrets.GITHUB_PAT }}

    - name: "Deploy reports to Github Pages (Dev branches)"
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh-pages
        FOLDER: public
        ACCESS_TOKEN: ${{ secrets.GITHUB_PAT }}
        TARGET_FOLDER: ${{ steps.extract_branch.outputs.branch }}