name: Testing

on: [push, pull_request]
env:
  TOOLCHAIN_PATH: .

jobs:
  test:
    runs-on: ubuntu-latest
    # container:
    #   image: ruby:2.6

    steps:
    - name: "Setup ruby 2.6"
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: actions/checkout@v1
    - name: "Install Gems"
      run: |
        bash setup/setup.sh
    - name: "Running unit tests"
      run: |
        rake toolchain:test
    - name: "Lint"
      run: |
        rake toolchain:lint
