name: Testing

on: [push, pull_request]
env:
  TOOLCHAIN_PATH: .

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6
    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: |
        rake toolchain:setup
    - name: "Running tests"
      run: |
        rake toolchain:test

  lint:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6
    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: |
        rake toolchain:setup
    - name: "Lint"
      run: |
        rake toolchain:lint
