name: Testing

on: [push, pull_request]
env:
  TOOLCHAIN_PATH: .

runs-on: ubuntu-latest
container:
  image: ruby:2.6

jobs:
  test:
    steps:
    - uses: actions/checkout@v1
    - name: Install rake
      run: |
        gem install rake
    - name: Setup
      run: |
        rake toolchain:setup
    - name: "Running tests"
      run: |
        rake toolchain:test

  lint:
    steps:
    - uses: actions/checkout@v1
    - name: Install rake
      run: |
        gem install rake
    - name: Setup
      run: |
        rake toolchain:setup
    - name: "Lint"
      run: |
        rake toolchain:lint
