name: Testing

on: [push, pull_request]
env:
  TOOLCHAIN_PATH: .

jobs:
  bats:
    runs-on: ubuntu-latest
    container:
      image: bats/bats:latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: bash stages/setup/setup_main.sh
    - name: Run tests
      run: |
        bats -r tests/

  nodejs:
    runs-on: ubuntu-latest
    container:
      image: node:13
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: echo "Running tests"

  ruby:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6
    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: bash stages/setup/setup_main.sh
    - name: "Running tests"
      run: |
        rake test

