name: Unit tests

on: [push, pull_request]
env:
  TOOLCHAIN_PATH: .

jobs:
  bash:
    runs-on: ubuntu-latest
    container:
      image: bats/bats:latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: bash stages/setup/setup_main.sh
    - name: Run tests
      run: |
        bats tests/bash/
