name: Unit tests

on: [push, pull_request]

jobs:
  bash:
    runs-on: ubuntu-latest
    container: bats/bats

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        bats tests/bash/*.bats
